import { MESSENGER_HOST, MESSENGER_PORT, MESSENGER_USER, MESSENGER_PASSWORD } from '@config';

export const amqpConnection = `amqp://${MESSENGER_USER}:${MESSENGER_PASSWORD}@${MESSENGER_HOST}:${MESSENGER_PORT}`;
