openapi: 3.0.0
info:
  title: Microservice Wallet
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Local

tags:
  - name: Transactions

paths:
  # Transactions
  /transactions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transactions'
      tags:
        - Transactions
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsModel'
          description: Response
        401:
          $ref: '#/components/responses/UnauthorizedError'
        422:
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
      security:
        - bearerAuth: []
    get:
      tags:
        - Transactions
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: type
          schema:
            type: string
        - in: query
          name: user_id
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionsModel'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        422:
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  # Transactions
  /balance:
    get:
      description: Esse endpoint deve retornar um consolidado das transações de CREDITO e DEBITO, fazendo o calculo do valor, de prefência que seja uma query fazendo o calculo
      tags:
        - Transactions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        401:
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - bearerAuth: []
components:
  schemas:
    Transactions:
      type: object
      required:
        - user_id
        - type
        - amount
      properties:
        user_id:
          type: string
        amount:
          type: integer
        type:
          type: string
          enum:
            - CREDIT
            - DEBIT
    TransactionsModel:
      type: object
      required:
        - user_id
        - type
        - amount
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        user_id:
          type: string
        amount:
          type: integer
        type:
          type: string
          enum:
            - CREDIT
            - DEBIT
        createdAt:
          type: string
        updatedAt:
          type: string
    BalanceResponse:
      type: object
      properties:
        debit:
          type: object
          properties:
            amount:
              type: integer
        credit:
          type: object
          properties:
            amount:
              type: integer
        all:
          type: object
          properties:
            amount:
              type: integer

    ValidationError:
      type: object
      required:
        - message
        - field_errors
      properties:
        message:
          type: string
        field_errors:
          type: object
          properties:
            field:
              type: object
              properties:
                id:
                  type: string
                message:
                  type: string

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Unauthorized
