version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: db-users
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
