version: '3.3'

services:
  api:
    image: node:16.14.0
    restart: unless-stopped
    container_name: nestjs-example-api
    working_dir: /usr/src/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "9229:9229"
    volumes:
      - ./:/usr/src/app
      - ./.volumes/logs:/root/.npm/_logs
    command: bash -c "yarn install && yarn start:debug"
    networks:
      - host_network

networks:
  host_network:
    external: true
    name: host


# accessible only by services inside the container